ALTER TABLE "balance_sheets" ALTER COLUMN "cash_and_equivalents" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "accounts_receivable" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "inventories" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "other_current_assets" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_current_assets" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "investiments" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "property_plant_equipment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "goodwill" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "intangible_assets" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "other_assets" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_assets" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "short_term_debt" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "accounts_payable" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "payroll" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "income_taxes" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "other_current_liabilities" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_current_liabilities" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "long_term_debt" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "other_liabilities" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_liabilities" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "common_stock" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "retained_capital" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "accumulated_compreensive_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_stakeholders_equity" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "balance_sheets" ALTER COLUMN "total_liabilities_and_stakeholders_equity" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "net_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "depreciation_amortization" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "deferred_income_tax" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "pension_contribution" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "accounts_receivable_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "inventories_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "other_current_assets_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "other_assets_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "accounts_payable_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "other_liabilities_change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "net_cash_from_operations" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "capital_expenditures" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "acquisitions" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "asset_sales" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "other_investing_activities" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "cash_flow_statements" ALTER COLUMN "net_cash_from_investing" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "companies" ALTER COLUMN "shares" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "net_sales" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "cost_of_goods_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "gross_profit" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "selling_general_administrative" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "research_and_development" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "other_expenses_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "operating_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "interest_expense" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "other_income_expense" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "pretax_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "income_taxes" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "net_income" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "weighted_avg_shares_outstanding" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_statements" ALTER COLUMN "weighted_avg_shares_outstanding_diluted" SET DATA TYPE bigint;